services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 30s
      timeout: 10s
      retries: 3

  url_discovery:
    build:
      context: .
      dockerfile: docker/discovery.Dockerfile
    command: python -m src.recruitment.services.discovery.main
    ports:
      - "8000:8000"
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_VHOST=/
      - RECRUITMENT_PATH=/app/src/recruitment/db/recruitment.db
    depends_on:
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./src/recruitment/db:/app/src/recruitment/db
      - recruitment_logs:/app/logs
      - ./csvs:/app/csvs:ro

  url_processing:
    build:
      context: .
      dockerfile: docker/processing.Dockerfile
    command: uvicorn src.recruitment.services.processing.main:app --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - RECRUITMENT_PATH=/app/src/recruitment/db/recruitment.db
    depends_on:
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./src/recruitment/db:/app/src/recruitment/db
      - recruitment_logs:/app/logs

volumes:
  recruitment_logs:

networks:
  recruitment_network:
    driver: bridge 