services:
  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - recruitment_network

  url_discovery:
    build:
      context: .
      dockerfile: docker/discovery.Dockerfile
    command: uvicorn src.recruitment.services.discovery.url_discovery_service:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq/
      - SEARCH_DAYS_BACK=7
      - SEARCH_INTERVAL_SECONDS=1800
      - GOOGLE_TLD=co.za
      - ENABLE_SCHEDULED_SEARCH=1
      - SCHEDULED_SEARCH_TERM='recruitment jobs South Africa'
      - SCHEDULED_SEARCH_INTERVAL_SECONDS=1800
      - GOOGLE_SEARCH_BATCH_SIZE=100
    depends_on:
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./src/recruitment/db:/app/src/recruitment/db
      - recruitment_logs:/app/logs
    networks:
      - recruitment_network

  url_processing:
    build:
      context: .
      dockerfile: docker/processing.Dockerfile
    command: uvicorn src.recruitment.services.processing.main:app --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq/
      - RECRUITMENT_DB_PATH=/app/src/recruitment/db/recruitment.db
    depends_on:
      rabbitmq:
        condition: service_healthy
      url_discovery:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./src/recruitment/db:/app/src/recruitment/db
      - recruitment_logs:/app/logs
    networks:
      - recruitment_network

volumes:
  recruitment_logs:

networks:
  recruitment_network:
    driver: bridge 