"""
Data models and schemas for the recruitment pipeline.
"""

from .url_models import (
    URLDiscoveryConfig,
    URLProcessingConfig,
    URLProcessingResult,
    transform_skills_response,
    SkillsResponse,
    SkillExperience,
    SkillExperienceResponse,
    AdvertResponse,
    ConfirmResponse,
    JobResponse,
    LocationResponse,
    ContactPersonResponse,
    AttributesResponse,
    AgencyResponse,
    CompanyResponse,
    IndustryResponse,
    BenefitsResponse,
    DutiesResponse,
    QualificationsResponse,
    LinkResponse,
    EmailResponse,
    CompanyPhoneNumberResponse,
    JobAdvertResponse,
)

__all__ = [
    "URLDiscoveryConfig",
    "URLProcessingConfig",
    "URLProcessingResult",
    "transform_skills_response",
    "SkillsResponse",
    "SkillExperience",
    "SkillExperienceResponse",
    "AdvertResponse",
    "ConfirmResponse",
    "JobResponse",
    "LocationResponse",
    "ContactPersonResponse",
    "AttributesResponse",
    "AgencyResponse",
    "CompanyResponse",
    "IndustryResponse",
    "BenefitsResponse",
    "DutiesResponse",
    "QualificationsResponse",
    "LinkResponse",
    "EmailResponse",
    "CompanyPhoneNumberResponse",
    "JobAdvertResponse",
]
